#!/usr/bin/env bash
#
# refresh-nsfw-list.sh — regenerate Singularity/Resources/nsfw-blocklist.txt
# from StevenBlack/hosts (porn extension, MIT-licensed). Run manually; the
# bundled list is static (no in-app updater in v1, per brief §12.2).
#
# Usage:  ./Scripts/refresh-nsfw-list.sh
#
set -euo pipefail

SRC="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts"
OUT="$(cd "$(dirname "$0")/.." && pwd)/Singularity/Resources/nsfw-blocklist.txt"

echo "Downloading $SRC ..."
raw="$(curl -fsSL "$SRC")"

{
  echo "# Singularity NSFW blocklist — generated by Scripts/refresh-nsfw-list.sh"
  echo "# Source: StevenBlack/hosts (porn extension, MIT). One host per line."
  # hosts file lines look like "0.0.0.0 pornhub.com"; keep the domain,
  # drop 'localhost' and the 0.0.0.0/127.0.0.1 sinks, dedupe, sort.
  echo "$raw" \
    | awk '/^0\.0\.0\.0|^127\.0\.0\.1/ { print $2 }' \
    | grep -v '^localhost$' \
    | grep -vi '^0\.0\.0\.0$' \
    | sort -u
} > "$OUT"

count="$(grep -vc '^#' "$OUT" || true)"
echo "Wrote $count hosts to $OUT"
